env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - standard
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - plugin:react-hooks/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 'latest'
  sourceType: 'module'
plugins:
  - react
  - '@typescript-eslint'
  - unused-imports
settings:
  react:
    version: 'detect'
rules:
  '@typescript-eslint/no-explicit-any': 1
  '@typescript-eslint/explicit-function-return-type':
    - 0
    - allowExpressions: true
  '@typescript-eslint/no-unused-vars': 1
  'unused-imports/no-unused-imports': 1
  camelcase: 0
  multiline-ternary: 0
  react/react-in-jsx-scope: 0
  react/prop-types: 0
  space-before-function-paren: 0
  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 1
  import/prefer-default-export: 0
  prefer-destructuring:
    - error
    - array: false
      object: true
  no-extra-semi: 0
  semi: 0
  indent: 0
  import/order:
    - warn
    - alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
      groups:
        - builtin
        - external
        - parent
        - sibling
        - index
      pathGroups:
        - pattern: react
          group: external
          position: before
      pathGroupsExcludedImportTypes:
        - builtin
globals:
  chrome: 'readonly'
ignorePatterns:
  - 'watch.js'
  - 'dist/**'
